#80表示注册到Zookeeper服务器的支付服务消费者端口号
server:
  port: 80

#服务别名----注册到Zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumerzk-order
  cloud:
    zookeeper:
      #Zookeeper的地址
      connect-string: 127.0.0.1:2181
